apiVersion: apps/v1
kind: Deployment
metadata:
  name: museum
spec:
  replicas: 1
  selector:
    matchLabels:
      app: museum
  template:
    metadata:
      labels:
        app: museum
    spec:
      containers:
      - name: museum
        image: "{{ .Values.museum.image }}"
        ports:
        - containerPort: {{ .Values.museum.ports.api }}
        - containerPort: {{ .Values.museum.ports.metrics }}
        env:
        - name: ENTE_DB_HOST
          value: "postgres"
        - name: ENTE_DB_PORT
          value: "{{ .Values.postgres.port }}"
        - name: ENTE_DB_NAME
          value: "{{ .Values.postgres.database }}"
        - name: ENTE_DB_USER
          value: "{{ .Values.postgres.username }}"
        - name: ENTE_DB_PASSWORD
          value: "{{ .Values.postgres.password }}"
        - name: ENTE_KEY_ENCRYPTION
          value: "{{ .Values.museum.env.ENTE_KEY_ENCRYPTION }}"
        - name: ENTE_KEY_HASH
          value: "{{ .Values.museum.env.ENTE_KEY_HASH }}"
        - name: ENTE_JWT_SECRET
          value: "{{ .Values.museum.env.ENTE_JWT_SECRET }}"
        - name: ENTE_S3_B2-EU-CEN_KEY
          value: "{{ .Values.museum.env.ENTE_S3_B2_EU_CEN_KEY }}"
        - name: ENTE_S3_B2-EU-CEN_SECRET
          value: "{{ .Values.museum.env.ENTE_S3_B2_EU_CEN_SECRET }}"
        - name: ENTE_S3_B2-EU-CEN_ENDPOINT
          value: "{{ .Values.museum.env.ENTE_S3_B2_EU_CEN_ENDPOINT }}"
        - name: ENTE_S3_B2-EU-CEN_REGION
          value: "{{ .Values.museum.env.ENTE_S3_B2_EU_CEN_REGION }}"
        - name: ENTE_S3_B2-EU-CEN_BUCKET
          value: "{{ .Values.museum.env.ENTE_S3_B2_EU_CEN_BUCKET }}"
        - name: ENTE_S3_ARE_LOCAL_BUCKETS
          value: "{{ .Values.museum.env.ENTE_S3_ARE_LOCAL_BUCKETS }}"

        - name: ENTE_INTERNAL_HARDCODED_OTT_LOCAL_DOMAIN_SUFFIX
          value: "{{ .Values.museum.env.ENTE_INTERNAL_HARDCODED_OTT_LOCAL_DOMAIN_SUFFIX }}"
        - name: ENTE_INTERNAL_HARDCODED_OTT_LOCAL_DOMAIN_VALUE
          value: "{{ .Values.museum.env.ENTE_INTERNAL_HARDCODED_OTT_LOCAL_DOMAIN_VALUE }}"
        volumeMounts:
        - name: custom-logs
          mountPath: /var/log
        readinessProbe:
          httpGet:
            path: /ping
            port: {{ default 8080 .Values.museum.ports.api }}
          initialDelaySeconds: 5
          periodSeconds: 10
      volumes:
      - name: custom-logs
        emptyDir: {}
