apiVersion: v1
kind: Service
metadata:
  name: web
{{- if .Values.web.service.annotations }}  
  annotations:
    {{- toYaml .Values.web.service.annotations | nindent 4 }}
{{- end }}
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - port: {{ .Values.web.ports.http }}
      targetPort: {{ .Values.web.ports.http }}
      name: http
  selector:
    app: web
